# Generated by Django 2.0.1 on 2018-01-27 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('reference', models.CharField(default='', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(default='', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='customers.CustomerAccount')),
            ],
        ),
        migrations.CreateModel(
            name='CodeExchanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchanged', to='exchange.Code')),
            ],
        ),
    ]
